global:
  security:
    # Enable this to allow the Bitnami Chart to use the AutoMQ image.
    allowInsecureImages: true
image:
  registry: automqinc
  repository: automq
  tag: 1.5.3-rc0-bitnami
  pullPolicy: Always
controller:
  replicaCount: 3
  resources:
    requests:
      cpu: "3"
      memory: "12Gi"
    limits:
      cpu: "4"
      memory: "16Gi"
  heapOpts: -Xmx6g -Xms6g -XX:MaxDirectMemorySize=6g -XX:MetaspaceSize=96m
  extraConfig: |
    elasticstream.enable=true
    autobalancer.client.auth.sasl.mechanism=PLAIN
    autobalancer.client.auth.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="inter_broker_user" password="interbroker-password-placeholder" user_inter_broker_user="interbroker-password-placeholder";
    autobalancer.client.auth.security.protocol=SASL_PLAINTEXT
    autobalancer.client.listener.name=INTERNAL
    s3.wal.cache.size=2147483648
    s3.block.cache.size=1073741824
    s3.stream.allocator.policy=POOLED_DIRECT
    s3.network.baseline.bandwidth=245366784
    # Replace the following with your bucket config.
    s3.ops.buckets=1@s3://${ops-bucket}?region=${region}&endpoint=${endpoint}
    s3.data.buckets=0@s3://${data-bucket}?region=${region}&endpoint=${endpoint}
    s3.wal.path=0@s3://${data-bucket}?region=${region}&endpoint=${endpoint}
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "automq"
      effect: "NoSchedule"
  persistence:
    # gp2 is the default storage class in AWS EKS.
    # If you're using a different storage class, please update it here.
    # Similar to Apache Kafka, AutoMQ requires a small disk to store metadata.
    storageClass: "gp2"
    size: 20Gi

broker:
  replicaCount: 1
  resources:
    requests:
      cpu: "3"
      memory: "12Gi"
    limits:
      cpu: "4"
      memory: "16Gi"
  heapOpts: -Xmx6g -Xms6g -XX:MaxDirectMemorySize=6g -XX:MetaspaceSize=96m
  extraConfig: |
    elasticstream.enable=true
    autobalancer.client.auth.sasl.mechanism=PLAIN
    autobalancer.client.auth.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="inter_broker_user" password="interbroker-password-placeholder" user_inter_broker_user="interbroker-password-placeholder";
    autobalancer.client.auth.security.protocol=SASL_PLAINTEXT
    autobalancer.client.listener.name=INTERNAL
    s3.wal.cache.size=2147483648
    s3.block.cache.size=1073741824
    s3.stream.allocator.policy=POOLED_DIRECT
    s3.network.baseline.bandwidth=245366784
    # Replace the following with your bucket config.
    s3.ops.buckets=1@s3://${ops-bucket}?region=${region}&endpoint=${endpoint}
    s3.data.buckets=0@s3://${data-bucket}?region=${region}&endpoint=${endpoint}
    s3.wal.path=0@s3://${data-bucket}?region=${region}&endpoint=${endpoint}
  tolerations:
    - key: "dedicated"
      operator: "Equal"
      value: "automq"
      effect: "NoSchedule"
  persistence:
    # gp2 is the default storage class in AWS EKS.
    # If you're using a different storage class, please update it here.
    # Similar to Apache Kafka, AutoMQ requires a small disk to store metadata.
    storageClass: "gp2"
    size: 20Gi
