{
 "title": "Broker Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster_id",
    "label": "Cluster Id",
    "query": {
     "query": "label_values(kafka_broker_active_count{instance_id=~\"$cmp_instance_id\", env_id=~\"$cmp_env_id\"},job)"
    }
   },
   {
    "name": "node_id",
    "label": "Node Id",
    "query": {
     "query": "label_values(kafka_server_connection_count{job=\"$cluster_id\"},instance)"
    }
   },
   {
    "name": "cmp_instance_id",
    "label": "CMP Instance Id",
    "query": {
     "query": "label_values(kafka_broker_active_count{env_id=~\"$cmp_env_id\"},instance_id)"
    }
   },
   {
    "name": "cmp_env_id",
    "label": "CMP Env Id",
    "query": {
     "query": "label_values(kafka_broker_active_count,env_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance, error) (rate(kafka_request_error_count_total{job=\"$cluster_id\", instance=~\"$node_id\", error!=\"NONE\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{error}}"
    }
   ]
  },
  {
   "title": "Connection Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by(instance, listener) (kafka_server_connection_count{job=\"$cluster_id\", instance=~\"$node_id\"})",
     "legendFormat": "Node-{{instance}}#{{listener}}"
    }
   ]
  },
  {
   "title": "Partition Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "kafka_partition_count{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}"
    }
   ]
  },
  {
   "title": "Partition Status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "kafka_stream_partition_status_statistics{job=\"$cluster_id\", instance=~\"$node_id\"}",
     "legendFormat": "Node-{{instance}}#{{status}}"
    }
   ]
  },
  {
   "title": "Bytes In",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(kafka_broker_network_io_bytes_total{job=\"$cluster_id\", direction=\"in\", instance=~\"$node_id\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes Out",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(kafka_broker_network_io_bytes_total{job=\"$cluster_id\", direction=\"out\", instance=~\"$node_id\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}"
    }
   ]
  },
  {
   "title": "Messages In",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(kafka_message_count_total{job=\"$cluster_id\", instance=~\"$node_id\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(topic, instance) (rate(kafka_network_io_bytes_total{job=\"$cluster_id\", direction=\"in\", instance=~\"$node_id\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(topic, instance) (rate(kafka_network_io_bytes_total{job=\"$cluster_id\", direction=\"out\", instance=~\"$node_id\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{topic}}"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by(topic, instance) (rate(kafka_message_count_total{job=\"$cluster_id\", instance=~\"$node_id\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{topic}}"
    }
   ]
  },
  {
   "title": "Produce QPS Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance, topic) (rate(kafka_topic_request_count_total{job=\"$cluster_id\", instance=~\"$node_id\", type=\"produce\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{topic}}"
    }
   ]
  },
  {
   "title": "Fetch QPS Per Topic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance, topic) (rate(kafka_topic_request_count_total{job=\"$cluster_id\", instance=~\"$node_id\", type=\"fetch\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{topic}}"
    }
   ]
  },
  {
   "title": "Total Throughput (Broker Level)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(kafka_request_count_total{job=\"$cluster_id\", instance=~\"$node_id\", type=~\"OffsetCommit|Produce|Fetch\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}"
    }
   ]
  },
  {
   "title": "Produce Throughput (Broker Level)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(kafka_request_count_total{job=\"$cluster_id\", instance=~\"$node_id\", type=\"Produce\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}"
    }
   ]
  },
  {
   "title": "Fetch Throughput (Broker Level)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(kafka_request_count_total{job=\"$cluster_id\", instance=~\"$node_id\", type=\"Fetch\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}"
    }
   ]
  },
  {
   "title": "Produce Throughput (Sum By Topic)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(kafka_topic_request_count_total{job=\"$cluster_id\", instance=~\"$node_id\", type=\"produce\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}"
    }
   ]
  },
  {
   "title": "Fetch Throughput (Sum By Topic)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(kafka_topic_request_count_total{job=\"$cluster_id\", instance=~\"$node_id\", type=\"fetch\"}[$__rate_interval]))",
     "legendFormat": "Node-{{instance}}#{{topic}}"
    }
   ]
  },
  {
   "title": "Produce Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(instance) (kafka_request_time_99p_milliseconds{job=\"$cluster_id\", instance=~\"$node_id\", type=\"Produce\"})",
     "legendFormat": "Node-{{instance}}#P99"
    },
    {
     "expr": "sum by(instance) (kafka_request_time_mean_milliseconds{job=\"$cluster_id\", instance=~\"$node_id\", type=\"Produce\"})",
     "legendFormat": "Node-{{instance}}#Avg"
    },
    {
     "expr": "sum by(instance) (kafka_request_time_50p_milliseconds{job=\"$cluster_id\", instance=~\"$node_id\", type=\"Produce\"})",
     "legendFormat": "Node-{{instance}}#P50"
    }
   ]
  },
  {
   "title": "Fetch Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(instance) (kafka_request_time_99p_milliseconds{job=\"$cluster_id\", instance=~\"$node_id\", type=\"Fetch\"})",
     "legendFormat": "Node-{{instance}}#P99"
    },
    {
     "expr": "sum by(instance) (kafka_request_time_mean_milliseconds{job=\"$cluster_id\", instance=~\"$node_id\", type=\"Fetch\"})",
     "legendFormat": "Node-{{instance}}#Avg"
    },
    {
     "expr": "sum by(instance) (kafka_request_time_50p_milliseconds{job=\"$cluster_id\", instance=~\"$node_id\", type=\"Fetch\"})",
     "legendFormat": "Node-{{instance}}#P50"
    }
   ]
  }
 ]
}