{
 "title": "Group Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster_id",
    "label": "Cluster Id",
    "query": {
     "query": "label_values(kafka_server_connection_count{instance_id=~\"$cmp_instance_id\", env_id=~\"$cmp_env_id\"},job)"
    }
   },
   {
    "name": "group_id",
    "label": "Consumer Group",
    "query": {
     "query": "label_values(kafka_group_commit_offset{topic=~\"$topic\", job=\"$cluster_id\"},consumer_group)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_group_commit_offset{job=\"$cluster_id\"},topic)"
    }
   },
   {
    "name": "partition",
    "label": "Partition",
    "query": {
     "query": "label_values(kafka_group_commit_offset{topic=~\"$topic\", job=\"$cluster_id\"},partition)"
    }
   },
   {
    "name": "cmp_env_id",
    "label": "CMP Env Id",
    "query": {
     "query": "label_values(kafka_broker_active_count,env_id)"
    }
   },
   {
    "name": "cmp_instance_id",
    "label": "CMP Instance Id",
    "query": {
     "query": "label_values(kafka_broker_active_count{env_id=~\"$cmp_env_id\"},instance_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Consumer Throughput",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by(consumer_group, topic) (max by(consumer_group, topic, partition) (rate(kafka_group_commit_offset{job=\"$cluster_id\", consumer_group=~\"$group_id\", topic=~\"$topic\", partition=~\"$partition\"}[$__rate_interval])))",
     "legendFormat": "{{consumer_group}}#{{topic}}"
    }
   ]
  },
  {
   "title": "Consumer Lag",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expression": "$B - $A", "type": "math" }
   ]
  },
  {
   "title": "Consumer Throughput By Partition",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by(consumer_group, topic, partition) (rate(kafka_group_commit_offset{job=\"$cluster_id\", consumer_group=~\"$group_id\", topic=~\"$topic\", partition=~\"$partition\"}[$__rate_interval]))",
     "legendFormat": "{{consumer_group}}#{{topic}}-{{partition}}"
    }
   ]
  },
  {
   "title": "Consumer Lag By Partition",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 14 },
   "targets": [
    { "expression": "$B - $A", "type": "math" }
   ]
  },
  {
   "title": "Consumer Commit Offsets",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "max by(consumer_group, topic, partition) (kafka_group_commit_offset{job=\"$cluster_id\", consumer_group=~\"$group_id\", topic=~\"$topic\", partition=~\"$partition\"})",
     "legendFormat": "{{consumer_group}}#{{topic}}-{{partition}}"
    }
   ]
  },
  {
   "title": "Log End Offset",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "max by(topic, partition) (kafka_log_end_offset{job=\"$cluster_id\", topic=~\"$topic\", partition=~\"$partition\"})",
     "legendFormat": "{{topic}}-{{partition}}"
    }
   ]
  }
 ]
}