version: '3.8'

services:
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: automq-kafdrop
    restart: unless-stopped
    ports:
      - "12001:9000"
    environment:
      # AutoMQ Broker Connection
      # Replace with your actual AutoMQ broker addresses
      KAFKA_BROKERCONNECT: "server1:9092"
      
      # Web Interface Configuration
      SERVER_SERVLET_CONTEXTPATH: "/"
      
      # JVM Memory Settings
      JVM_OPTS: "-Xms32M -Xmx64M"
      
      # Message Format Configuration
      # Options: DEFAULT, AVRO, PROTOBUF
      MESSAGE_FORMAT: "DEFAULT"
      MESSAGE_KEYFORMAT: "DEFAULT"
      
      # Schema Registry Configuration (uncomment if using)
      # SCHEMAREGISTRY_CONNECT: "http://schema-registry:8081"
      # SCHEMAREGISTRY_AUTH: "username:password"
      
      # Additional Kafka Client Properties (uncomment if needed)
      # CMD_ARGS: "--kafka.properties.file=/opt/kafdrop/kafka-client.properties"
    
    # Health Check
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9000/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Volume Mounts (uncomment if using custom configurations)
    # volumes:
    #   - ./kafka-client.properties:/opt/kafdrop/kafka-client.properties:ro
    #   - ./protobuf-desc:/var/protobuf_desc:ro
    
    # Network Configuration
    networks:
      - automq_net

  # Optional: Schema Registry (uncomment if needed)
  # schema-registry:
  #   image: confluentinc/cp-schema-registry:latest
  #   container_name: automq-schema-registry
  #   restart: unless-stopped
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     SCHEMA_REGISTRY_HOST_NAME: schema-registry
  #     SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "localhost:9092"
  #     SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:8081"
  #   networks:
  #     - automq-network
  #   depends_on:
  #     - kafdrop

networks:
  automq_net:
    external: true
    name: automq_net