version: '3.8'

services:
  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    ports:
      - "8080:8080"
    environment:
      # Kafka/AutoMQ broker configuration
      KAFKA_BROKERS: "server1:9092"
      # Optional: Enable TLS if your AutoMQ cluster uses TLS
      # KAFKA_TLS_ENABLED: "true"
      # Optional: Enable SASL if your AutoMQ cluster uses SASL authentication
      # KAFKA_SASL_ENABLED: "true"
      # KAFKA_SASL_MECHANISM: "PLAIN"
      # KAFKA_SASL_USERNAME: "your-username"
      # KAFKA_SASL_PASSWORD: "your-password"
      
      # Console configuration
      SERVER_LISTENPORT: "8080"
      LOGGING_LEVEL: "info"
      
    networks:
      - automq_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/api/cluster"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  automq_net:
    external: true
    name: automq_net