services:
  automq-java-examples:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: automq-kafka-examples
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m
      # Default to single-node mode and adjust according to the mode you deployed.
      - BOOTSTRAP_SERVERS=server1:9092
    networks:
      - automq_net
    restart: "no"

networks:
  automq_net:
    external: true
    name: automq_net