services:
  automq-java-examples:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: automq-kafka-examples
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m
      - BOOTSTRAP_SERVERS=${BOOTSTRAP_SERVERS:-localhost:9092}
    # Use host network mode for direct access to host services
    network_mode: host
    restart: "no"