version: '3.8'

services:
  automq-javascript-examples:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: automq-javascript-examples
    environment:
      - NODE_ENV=production
      - BOOTSTRAP_SERVERS=${BOOTSTRAP_SERVERS:-localhost:9092}
    networks:
      - automq_net
    restart: "no"

networks:
  automq_net:
    external: true