apiVersion: v1
kind: Pod
metadata:
  name: load-test-pod
  namespace: default
  labels:
    app: load-test
    purpose: testing
spec:
  # 部署到 loadtest node group
  nodeSelector:
    workload-type: loadtest
  
  containers:
  - name: load-test-container
    image: ubuntu:22.04
    
    # 保持容器运行
    command: ["/bin/bash"]
    args: ["-c", "sleep infinity"]
    
    # 环境变量
    env:
    - name: DEBIAN_FRONTEND
      value: "noninteractive"
    
    # 资源限制
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "2Gi"
        cpu: "1000m"
    # 安全上下文
    securityContext:
      runAsUser: 0  # root 用户，方便安装软件
      allowPrivilegeEscalation: true
  # 重启策略
  restartPolicy: Always