version: "3.9"
services:
  minio:
    image: minio/minio:RELEASE.2024-09-22T00-00-00Z
    command: server /data --console-address :9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports: ["9000:9000","9001:9001"]

  polaris:
    image: apache/polaris:1.1.0
    ports: ["8181:8181"]
    volumes:
      - ./configs/polaris.yaml:/opt/polaris/config.yaml:ro
    command: ["/opt/polaris/bin/polaris", "server", "-c", "/opt/polaris/config.yaml"]

  automq:
    image: automqinc/automq:latest
    depends_on: [minio, polaris]
    environment:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      AWS_ENDPOINT_OVERRIDE: http://minio:9000
      AUTOMQ_CONFIG: /opt/automq/automq.properties
    volumes:
      - ./configs/automq.properties:/opt/automq/automq.properties:ro
    ports: ["9092:9092"]

  spark:
    image: bitnami/spark:3.5
    depends_on: [polaris]
    environment:
      - SPARK_MODE=client
    volumes:
      - ./scripts:/workspace/scripts:ro
