mock_provider "automq" {
  mock_resource "automq_kafka_instance" {
    defaults = {
      id     = "instance-example"
      status = "RUNNING"
    }
  }
}

mock_provider "http" {
  mock_data "http" {
    defaults = {
      status_code   = 200
      response_body = <<-HTML
        <script>window.__AUTOMQ_GLOBAL_DATA__ = {"usageBasedPricingEnabled":true,"usageBasedPricingAvailable":true};</script>
      HTML
    }
  }
}

variables {
  console_endpoint   = "http://console.example:8080"
  console_access_key = "access-key"
  console_secret_key = "secret-key"
  environment_id     = "env-example"

  broker_networks = [
    { zone = "us-east-1a", subnets = ["subnet-aaaaaaaaaaaaaaaaa"] },
    { zone = "us-east-1b", subnets = ["subnet-bbbbbbbbbbbbbbbbb"] },
    { zone = "us-east-1c", subnets = ["subnet-ccccccccccccccccc"] },
  ]

  data_bucket_name   = "automq-data-example"
  dns_zone_id        = "Z0123456789"
  instance_role_name = "automq-data-plane-example"
}

run "creates_bucket_scoped_iaas_instance" {
  command = apply

  assert {
    condition     = automq_kafka_instance.this.compute_specs.deploy_type == "IAAS"
    error_message = "The EC2 Custom example must always create an IAAS Instance."
  }

  assert {
    condition = (
      automq_kafka_instance.this.compute_specs.pricing_mode == "UsageBased" &&
      automq_kafka_instance.this.compute_specs.reserved_node_count == 3 &&
      automq_kafka_instance.this.compute_specs.instance_types[0] == "m7g.xlarge"
    )
    error_message = "The quick path must default to a three-node m7g.xlarge UsageBased Instance."
  }

  assert {
    condition     = automq_kafka_instance.this.compute_specs.instance_role == "automq-data-plane-example"
    error_message = "The IAAS Instance must use the dedicated data-plane Role name expected by Console 8.3.16."
  }

  assert {
    condition     = automq_kafka_instance.this.compute_specs.data_buckets[0].bucket_name == "automq-data-example" && automq_kafka_instance.this.compute_specs.dns_zone == "Z0123456789"
    error_message = "The IAAS Instance must use the Console stage data bucket and private DNS zone."
  }

  assert {
    condition     = automq_kafka_instance.this.compute_specs.networks == output.broker_networks
    error_message = "The IAAS Instance must receive the network payload generated by the Console stage."
  }

  assert {
    condition     = automq_kafka_instance.this.features.wal_mode == "EBSWAL"
    error_message = "The quick path must default to EBSWAL."
  }
}

run "role_arn_is_rejected" {
  command = plan

  variables {
    instance_role_name = "arn:aws:iam::123456789012:role/automq-data-plane-example"
  }

  expect_failures = [var.instance_role_name]
}

run "two_zone_topology_is_rejected" {
  command = plan

  variables {
    broker_networks = [
      { zone = "us-east-1a", subnets = ["subnet-aaaaaaaaaaaaaaaaa"] },
      { zone = "us-east-1b", subnets = ["subnet-bbbbbbbbbbbbbbbbb"] },
    ]
  }

  expect_failures = [var.broker_networks]
}

run "tls_without_certificate_configuration_is_rejected" {
  command = plan

  variables {
    transit_encryption_modes = ["tls"]
  }

  expect_failures = [var.transit_encryption_modes]
}

run "duplicate_broker_network_is_rejected" {
  command = plan

  variables {
    broker_networks = [
      { zone = "us-east-1a", subnets = ["subnet-aaaaaaaaaaaaaaaaa"] },
      { zone = "us-east-1a", subnets = ["subnet-bbbbbbbbbbbbbbbbb"] },
      { zone = "us-east-1c", subnets = ["subnet-aaaaaaaaaaaaaaaaa"] },
    ]
  }

  expect_failures = [var.broker_networks]
}

run "unavailable_usage_based_subscription_is_rejected" {
  command = plan

  override_data {
    target = data.http.console_capabilities
    values = {
      status_code   = 200
      response_body = <<-HTML
        <script>window.__AUTOMQ_GLOBAL_DATA__ = {"usageBasedPricingEnabled":true,"usageBasedPricingAvailable":false};</script>
      HTML
    }
  }

  expect_failures = [terraform_data.usage_based_subscription_preflight]
}
