#!/bin/bash
set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

print_info() {
    printf "${GREEN}[INFO]${NC} %s\n" "$1"
}

print_warn() {
    printf "${YELLOW}[WARN]${NC} %s\n" "$1"
}

print_error() {
    printf "${RED}[ERROR]${NC} %s\n" "$1"
}

print_header() {
    echo ""
    echo "=============================================="
    echo " AutoMQ Local Deployment Setup"
    echo "=============================================="
    echo ""
}

# Pre-flight checks
check_prerequisites() {
    print_info "Checking prerequisites..."
    local has_error=0

    # Check kubectl
    if ! command -v kubectl &> /dev/null; then
        print_error "kubectl is not installed. Please install kubectl first."
        print_info "  Installation guide: https://kubernetes.io/docs/tasks/tools/"
        has_error=1
    else
        print_info "✓ kubectl found: $(kubectl version --client --short 2>/dev/null || kubectl version --client -o yaml | grep gitVersion | head -1)"
    fi

    # Check helm
    if ! command -v helm &> /dev/null; then
        print_error "helm is not installed. Please install helm first."
        print_info "  Installation guide: https://helm.sh/docs/intro/install/"
        has_error=1
    else
        print_info "✓ helm found: $(helm version --short)"
    fi

    # Check kubernetes cluster connectivity
    if command -v kubectl &> /dev/null; then
        if ! kubectl cluster-info &> /dev/null; then
            print_error "Cannot connect to Kubernetes cluster. Please ensure your cluster is running and kubectl is configured."
            has_error=1
        else
            print_info "✓ Kubernetes cluster is accessible"
            
            # Check cluster resources
            local node_count
            node_count=$(kubectl get nodes --no-headers 2>/dev/null | wc -l | tr -d ' ')
            print_info "  Cluster nodes: $node_count"
        fi
    fi

    if [ $has_error -eq 1 ]; then
        echo ""
        print_error "Prerequisites check failed. Please resolve the issues above and try again."
        exit 1
    fi

    print_info "All prerequisites satisfied!"
    echo ""
}

# Detect CPU architecture
detect_architecture() {
    local arch
    arch=$(uname -m)
    case $arch in
        arm64|aarch64)
            NODE_ARCH="arm64"
            ;;
        x86_64|amd64)
            NODE_ARCH="amd64"
            ;;
        *)
            print_warn "Unknown architecture: $arch, defaulting to amd64"
            NODE_ARCH="amd64"
            ;;
    esac
    print_info "Detected CPU architecture: $NODE_ARCH"
}

# Generate automq-values.yaml
generate_values() {
    print_info "Generating automq-values.yaml..."
    
    cat <<EOF > automq-values.yaml
# AutoMQ Helm Values
# Generated by setup.sh
# Architecture: ${NODE_ARCH}

global:
  automqInstanceId: "automq-demo-cluster"
  cloudProvider:
    name: "noop"
    credentials: "static://?accessKey=admin&secretKey=automq_demo_secret"
  nodeAffinities:
    - key: "kubernetes.io/arch"
      values:
        - "${NODE_ARCH}"
  config: |
    s3.ops.buckets=0@s3://automq-ops?region=us-east-1&endpoint=http://minio.default.svc.cluster.local:9000&pathStyle=true
    s3.data.buckets=0@s3://automq-data?region=us-east-1&endpoint=http://minio.default.svc.cluster.local:9000&pathStyle=true
    s3.wal.path=0@s3://automq-data?region=us-east-1&endpoint=http://minio.default.svc.cluster.local:9000&pathStyle=true

controller:
  replicas: 3
  resources:
    requests:
      cpu: "1000m"
      memory: "2Gi"
    limits:
      cpu: "2000m"
      memory: "4Gi"
  env:
    - name: "KAFKA_S3_ACCESS_KEY"
      value: "admin"
    - name: "KAFKA_S3_SECRET_KEY"
      value: "automq_demo_secret"
    - name: "KAFKA_HEAP_OPTS"
      value: "-Xmx2g -Xms2g"
  persistence:
    wal:
      enabled: false

broker:
  replicas: 0
  env:
    - name: "KAFKA_S3_ACCESS_KEY"
      value: "admin"
    - name: "KAFKA_S3_SECRET_KEY"
      value: "automq_demo_secret"
  persistence:
    wal:
      enabled: false
EOF

    print_info "✓ Generated automq-values.yaml"
}

# Print next steps
print_next_steps() {
    echo ""
    echo "=============================================="
    echo " Setup Complete!"
    echo "=============================================="
    echo ""
    echo "Next steps:"
    echo ""
    echo "1. Install MinIO:"
    echo "   helm repo add minio https://charts.min.io/"
    echo ""
    echo "   helm install minio minio/minio \\"
    echo "     --set rootUser=admin \\"
    echo "     --set rootPassword=automq_demo_secret \\"
    echo "     --set \"buckets[0].name=automq-data,buckets[0].policy=none,buckets[0].purge=false\" \\"
    echo "     --set \"buckets[1].name=automq-ops,buckets[1].policy=none,buckets[1].purge=false\" \\"
    echo "     --set mode=standalone \\"
    echo "     --set service.type=ClusterIP \\"
    echo "     --set persistence.enabled=false \\"
    echo "     --set resources.requests.memory=512Mi \\"
    echo "     --set resources.requests.cpu=250m \\"
    echo "     --set resources.limits.memory=2Gi \\"
    echo "     --set resources.limits.cpu=2 \\"
    echo "     --wait"
    echo ""
    echo "2. Install AutoMQ:"
    echo "   helm install automq oci://automq.azurecr.io/helm/automq-enterprise-chart \\"
    echo "     --version 5.3.4 \\"
    echo "     -f automq-values.yaml \\"
    echo "     --wait"
    echo ""
    echo "3. Verify installation:"
    echo "   ./verify.sh"
    echo ""
    echo "For cleanup, run: ./cleanup.sh"
    echo ""
}

# Main
main() {
    print_header
    check_prerequisites
    detect_architecture
    generate_values
    print_next_steps
}

main "$@"
